name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}
          username: Wojtek--
          show_icons: true
          count_private: true
          theme: tokyonight
